name       : opensubdiv
version    : 3.4.0
release    : 2
source     :
    - https://github.com/PixarAnimationStudios/OpenSubdiv/archive/v3_4_0.tar.gz : d932b292f83371c7518960b2135c7a5b931efb43cdd8720e0b27268a698973e4
license    : Apache-2.0
component  : multimedia.library
summary    : An Open-Source subdivision surface library
description: |
    OpenSubdiv is a set of open source libraries that implement high performance subdivision surface (subdiv) evaluation on massively parallel CPU and GPU architectures.

    This codepath is optimized for drawing deforming subdivs with static topology at interactive framerates. The resulting limit surface matches Pixar's Renderman to numerical precision.
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(glfw3)
    - pkgconfig(libglvnd)
    - pkgconfig(xcb)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xrandr)
    - intel-tbb-devel
setup      : |
    %cmake_ninja \
      -DNO_EXAMPLES:BOOL=TRUE \
      -DNO_TUTORIALS:BOOL=TRUE \
      -DNO_PTEX:BOOL=TRUE \
      -DNO_DOC:BOOL=TRUE \
      -DNO_TBB:BOOL=TRUE \
      -DNO_CUDA:BOOL=TRUE \
      -DNO_OPENCL:BOOL=TRUE \
      -DNO_METAL:BOOL=TRUE \
      -DOpenGL_GL_PREFERENCE:STRING="GLVND"
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -v $installdir/usr/lib/*.a
