name       : opensubdiv
version    : 3.4.4
release    : 6
source     :
    - https://github.com/PixarAnimationStudios/OpenSubdiv/archive/refs/tags/v3_4_4.tar.gz : 20d49f80a2b778ad4d01f091ad88d8c2f91cf6c7363940c6213241ce6f1048fb
license    : Apache-2.0
homepage   : https://graphics.pixar.com/opensubdiv/
component  : multimedia.library
summary    : An Open-Source subdivision surface library
description: |
    OpenSubdiv is a set of open source libraries that implement high performance subdivision surface (subdiv) evaluation on massively parallel CPU and GPU architectures.

    This codepath is optimized for drawing deforming subdivs with static topology at interactive framerates. The resulting limit surface matches Pixar's Renderman to numerical precision.
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(glfw3)
    - pkgconfig(libglvnd)
    - intel-tbb-devel
    - ptex-devel
setup      : |
    %patch -p1 < $pkgfiles/correct-soname-cmake.patch

    %cmake_ninja \
      -DNO_CUDA=ON \
      -DNO_DOC=ON \
      -DNO_EXAMPLES=OFF \
      -DNO_GLEW=OFF \
      -DNO_METAL=ON \
      -DNO_OPENCL=ON \
      -DNO_OPENGL=OFF \
      -DNO_PTEX=OFF \
      -DNO_TUTORIALS=ON \
      -DOpenGL_GL_PREFERENCE:STRING="GLVND"
build      : |
    %ninja_build
install    : |
    %ninja_install
    rename stringify osd_stringify $installdir/usr/bin/stringify
    rm -v $installdir/usr/lib/*.a
